/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.practice;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("This is being run by my test");
        return true;
    }

    public String giveIceCream(String name){ // Garhett
        return  "Give " + name + " chocolate cookie dough ice cream"; // Give Garhett chocolate cookie dough ice cream
    }
}
