/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package qGeneric;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main (String[] args){
        Stack<Cat> cats = new Stack<>();
        cats.push(new Cat());
        cats.push(new Cat());
    }
}
