/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package animalShelter;

import java.util.LinkedList;

public class App {

    public static void main(String[] args) throws ClassNotFoundException {
        AnimalShelter shelter = new AnimalShelter();
        shelter.enQueue(new Cat("Garfield"));
        shelter.enQueue(new Cat("Snowdrop"));
        shelter.enQueue(new Dog("Clifford"));
        shelter.enQueue(new Dog("Ginger"));
        shelter.enQueue(new Cat("5"));
        shelter.enQueue(new Cat("6"));
        shelter.enQueue(new Dog("7"));
        shelter.enQueue(new Dog("8"));

        System.out.println(shelter.deQueue(LinkedList.class).name);
        System.out.println(shelter.deQueue(Dog.class).name);
        System.out.println(shelter.deQueue(Dog.class).name);
        System.out.println(shelter.deQueue(Dog.class).name);
        System.out.println(shelter.deQueue().name);
        System.out.println(shelter.deQueue().name);
        System.out.println(shelter.deQueue().name);
        System.out.println(shelter.deQueue().name);
    }
}
