/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gsonPractice;

import com.google.gson.Gson;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException {
        Gson gson = new Gson();

        Unicorn barry = new Unicorn("Pink", "white", 100, "Barry");
        System.out.println(barry);
        String barryAsJson = gson.toJson(barry);
        System.out.println(barryAsJson);
        // barryAsJson.prance() will not work because barryAsJson is not a unicorn, he is a string

        Unicorn barryThatOnceWasJsonButNowIsUnicorn = gson.fromJson(barryAsJson, Unicorn.class);
        // in Java when I type `Unicorn` I am not accessing the class, I am accessing the consctructor
        // EX new Unicorn
        barryThatOnceWasJsonButNowIsUnicorn.prance();

        String someJson = "{\"name\":\"Matthew\"}";
        Unicorn matthew = gson.fromJson(someJson, Unicorn.class);
        System.out.println(matthew);
        matthew.prance();
        // if less is provided to gson, it skips the missing fields (property)

        String someJsonKrystian = "{\"name\":\"Krystian\", \"cool\":true}";
        Unicorn krystian = gson.fromJson(someJsonKrystian, Unicorn.class);
        System.out.println(krystian);
        krystian.prance();
        // if more is provided, it ignores everything that is not a field in the class we are converting to

        // turn barry into a cupcake
        Cupcake barryAsCupcake = gson.fromJson(barryAsJson, Cupcake.class);
        System.out.println(barryAsCupcake);
        barryAsCupcake.getEaten();

        File barryFile = new File("src/main/resources/barry.json");
        barryFile.createNewFile();
        FileWriter barryFileWriter = new FileWriter("src/main/resources/barry.json");
        gson.toJson(barry, barryFileWriter);
        barryFileWriter.close();

        Scanner fairyDustScanner = new Scanner(new File("src/main/resources/fairyDust.json"));
        String allTheFairyJson = fairyDustScanner.nextLine();
        Unicorn fairyDust = gson.fromJson(allTheFairyJson, Unicorn.class);
        System.out.println(fairyDust);
        fairyDust.prance();
    }
}
