/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package internet;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

public class App {

    public static void main(String[] args) throws IOException {
        // http://numbersapi.com/20
        URL url = new URL("http://numbersapi.com");


        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        connection.setRequestMethod("GET");

        BufferedReader input = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        String oneLine = input.readLine();
        StringBuffer entireStringFromResponse = new StringBuffer();

        while(oneLine != null){
            entireStringFromResponse.append(oneLine);
            oneLine = input.readLine();
        }

        input.close();
        System.out.println(entireStringFromResponse);
    }
}
