/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demos;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println("printing args ===============");
        for(String arg : args){
            System.out.println(arg);
        }
        System.out.println("end printing args ==============");
//        System.out.println(new App().getGreeting());
//        System.out.println(Pastry.yummy);
//        Pastry apricot = new Pastry("apricot", true, false, "circle");
//        System.out.println(apricot.madeOf);
//        System.out.println(apricot.yummy);
//        System.out.println(apricot.fruit);
//        System.out.println(apricot.shape);
//        System.out.println(apricot.toString());
//        System.out.println(apricot);
//        Pastry nut = new Pastry(null, true, true, "triangle");
//        System.out.println(nut);
//        System.out.println(nut.hot);
//        System.out.println(nut.bake());
//        System.out.println(nut.hot);

        Bakery krispyKreme = new Bakery();
        krispyKreme.makePastry("jelly", true, false, "doughnut");
        krispyKreme.makePastry("chocolate", false, false, "doughnut");
        krispyKreme.makePastry("boston creme", false, false, "doughnut");
        krispyKreme.makePastry("straberry", false, false, "doughnut");

        krispyKreme.displayPastries();
        krispyKreme.sellPastry(1);
        krispyKreme.sellPastry(2);
        krispyKreme.sellPastry(0);
        krispyKreme.displayPastries();
    }
}
