import java.nio.file.FileSystems;
import java.nio.file.Path;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        for(String arg : args) {
            System.out.println(arg);
        }
        // find an image
        // read the image
        Bitmap bmp = new Bitmap(); // instance of the class you want to work with ``Bitmap`
        // 2. the bitmap will need to keep track of its own data
            // - if you have variables holding onto bitmap data in App, those need to be instance vars
        // 3. any behavior / methods in app need to be transfered into methods in `Bitmap`
            // those methods should modify the instance variables of `Bitmap`

        // TODO: test bitmap

        // mess with the image
        if(args[0].equals("flip")) {
            System.out.println("we are going to flip this bitmap");
            bmp.flipVertically();
        } else if(args[0].equals( "gray")){
            System.out.println("lets grayify this");
            bmp.grayscale();
        } else {
            System.out.println("I can only flip bitmaps right now");
        }

        // output the image
        bmp.save(FileSystems.getDefault().getPath("resources", "img_after.bmp"));
    }
}
