/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package maps;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public void listStuff () {
        String[] names = new String[]{"Nicholas", "Ginger"};
        ArrayList<String> peeps = new ArrayList<>();

        peeps.add("Nicholas");
        peeps.add("Matthew");
        peeps.add("Claudio");
        peeps.add("Leah");
        peeps.add("Leah");
        peeps.add("Leah");
        peeps.add("Leah");
        peeps.add("Leah");
        peeps.add("Leah");
        peeps.add("Leah");
        System.out.println("a");
        System.out.println(peeps); // there is a toString method
        System.out.println("a");
        System.out.println(peeps.get(0)); // peeps[0]

        for(int i = 0; i < peeps.size(); i++){
            System.out.println(peeps.get(i) + ", nice to see you");
        }

        for(String peepPotato : peeps){
            System.out.println(peepPotato + " i am iterated over by peep : peeps");
        }

        HashSet<String> iceCreamWeBuyAtTheStore = new HashSet<>();
        iceCreamWeBuyAtTheStore.add("Vanilla");
        iceCreamWeBuyAtTheStore.add("Chocolate");
        iceCreamWeBuyAtTheStore.add("Vanilla"); // will bounce / do nothing
        iceCreamWeBuyAtTheStore.add("Vanilla");
        iceCreamWeBuyAtTheStore.add("Vanilla");
        iceCreamWeBuyAtTheStore.add("Vanilla");
        iceCreamWeBuyAtTheStore.add("Vanilla");

        if(iceCreamWeBuyAtTheStore.contains("Vanilla")){
            System.out.println(" we already have vanilla, go get mint chip");
        }

        System.out.println(iceCreamWeBuyAtTheStore);

        // Hashmap === object in js
        // set of key value pairs
        // look up time is O(1)

        HashMap<String, Integer> iceCreamCost = new HashMap<>();
        iceCreamCost.put("Mint Chip", 20);
        iceCreamCost.put("Rocky Road", 21);
        System.out.println(iceCreamCost);
        iceCreamCost.put("Mint Chip", 25);
        System.out.println(iceCreamCost);
        System.out.println(iceCreamCost.get("Mint Chip"));;

        HashMap<String[], int[]> school = new HashMap<>();
        String[] gingerClass = new String[]{"Ginger", "Snowdrop"};
        school.put(gingerClass, new int[]{99, 72});
        school.put(new String[]{"Star", "Raven" ,"Robin"}, new int[]{92, 91, 65});
        System.out.println(school);

        System.out.println(school.get(gingerClass)[0]);

        for(String[] classNames : school.keySet()){
            System.out.println(classNames[0] + classNames[1]);
        }

        

    }
}
